/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmManterDepartamento.java
 *
 * Created on May 22, 2009, 10:50:36 AM
 */
package view;

import control.CtrManterDepartamento;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Departamento;

/**
 *
 * @author elio
 */
public class FrmManterDepartamento extends javax.swing.JFrame {
    //declaracao dos atributos

    CtrManterDepartamento ctrManterDepartamento;
    Departamento depart;

    /** Creates new form FrmManterDepartamento */
    public FrmManterDepartamento() {
        initComponents();
         //inicia os atributos
        ctrManterDepartamento = new CtrManterDepartamento();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnIncluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLstDepartamentos = new javax.swing.JList();
        jBtnExcluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtArea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnIncluirMouseClicked(evt);
            }
        });

        jLstDepartamentos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLstDepartamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLstDepartamentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jLstDepartamentos);

        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnExcluirMouseClicked(evt);
            }
        });

        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAlterarMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Departamento"));

        jLabel1.setText("Nome");

        jLabel2.setText("Área");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(50, 50, 50)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtArea)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnAlterar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnAlterar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
        //carrega lista de departamentos
        DefaultListModel listModel = new DefaultListModel();
        List listDepartamento = new ArrayList();
        listDepartamento = ctrManterDepartamento.carregarDepartamentos();
        if (listDepartamento != null) {
            Iterator i = listDepartamento.iterator();
            while (i.hasNext()) {
                Departamento deptList = (Departamento) i.next();
                listModel.addElement(deptList);
            }
            jLstDepartamentos.setModel(listModel);
        }
    }//GEN-LAST:event_formWindowActivated

    private void jLstDepartamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLstDepartamentosMouseClicked
        //recupera o departamento selecionado
        depart = (Departamento) jLstDepartamentos.getSelectedValue();

        //exibe os dados do departamento
        if (depart != null) {
            jTxtNome.setText(depart.getNome());
            jTxtArea.setText(depart.getArea());
        } else {
            JOptionPane.showMessageDialog(null, "Objeto não Encontrado!");
        }
    }//GEN-LAST:event_jLstDepartamentosMouseClicked

    private void jBtnIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnIncluirMouseClicked
         //atribui valores para o departamento
        depart = new Departamento();
        depart.setNome(jTxtNome.getText());
        depart.setArea(jTxtArea.getText());

        //inclui departamento
        if (ctrManterDepartamento.gravarDepartamento(depart) == 1) {
            JOptionPane.showMessageDialog(this, "Objeto persistido");
        } else if (ctrManterDepartamento.gravarDepartamento(depart) == 2) {
            JOptionPane.showMessageDialog(this, "Objeto não persistido");
        } else {
            JOptionPane.showMessageDialog(this, "Nome repetido");
        }
    }//GEN-LAST:event_jBtnIncluirMouseClicked

    private void jBtnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnExcluirMouseClicked
      //recupera o departamento selecionado
        depart = (Departamento) jLstDepartamentos.getSelectedValue();

        //exclui departamento
        if (depart != null) {
            if (ctrManterDepartamento.excluirDepartamento(depart)) {
                JOptionPane.showMessageDialog(null, "Objeto Exclu�do");
            } else {
                JOptionPane.showMessageDialog(null, "Objeto n�o exclu�do");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o Objeto");
        }
    }//GEN-LAST:event_jBtnExcluirMouseClicked

    private void jBtnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAlterarMouseClicked
         //recupera o departamento selecionado
        depart = (Departamento) jLstDepartamentos.getSelectedValue();
        //altera o departamento
        if (depart != null) {
            depart.setNome(jTxtNome.getText());
            depart.setArea(jTxtArea.getText());

            if (ctrManterDepartamento.alterarDepartamento(depart)) {
                JOptionPane.showMessageDialog(this, "Objeto persistido");

            } else {
                JOptionPane.showMessageDialog(this, "Objeto n�o persistido");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Objeto n�o localizado");
        }
    }//GEN-LAST:event_jBtnAlterarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmManterDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jLstDepartamentos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtArea;
    private javax.swing.JTextField jTxtNome;
    // End of variables declaration//GEN-END:variables
}
